name: CI

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: pnpm

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: TypeScript check
        run: pnpm tsc --noEmit

      - name: Lint code
        run: pnpm run lint

      - name: Build development (Vite)
        run: pnpm run dev -- --build

      - name: Build production (Tauri)
        run: pnpm run tauri build
